# Generated by Django 4.1.2 on 2024-02-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("approval_tickets", "0001_initial"),
        ("approval_groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalGroupProxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "approval_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_group_proxies",
                        to="approval_tickets.approvalticketproxy",
                    ),
                ),
            ],
        ),
    ]
