# Generated by Django 4.1.2 on 2024-02-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_levels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_status",
                    models.CharField(
                        choices=[("accept", "Accept"), ("deny", "Deny")], max_length=255
                    ),
                ),
                ("action_message", models.TextField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="approval_attachments"
                    ),
                ),
                (
                    "approval_level",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_mark",
                        to="approval_levels.approvallevel",
                    ),
                ),
            ],
        ),
    ]
