# Generated by Django 5.1.8 on 2025-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_rate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
