# Generated by Django 5.1.8 on 2025-05-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_rate", "0003_currency_created_at_exchangerate_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "received_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_transactions",
                        to="exchange_rate.currency",
                    ),
                ),
                (
                    "rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exchange_rate.exchangerate",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_transactions",
                        to="exchange_rate.currency",
                    ),
                ),
            ],
        ),
    ]
