# Generated by Django 5.1.8 on 2025-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_rate", "0004_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Buy", "Buy"), ("Sell", "Sell"), ("Transfer", "Transfer")],
                default="Buy",
                max_length=10,
            ),
        ),
    ]
