# Generated by Django 5.1.8 on 2025-05-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_rate", "0009_exchangeagreement_transaction_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exchange_rate.exchangeproposal",
            ),
        ),
    ]
