# Generated by Django 5.0.4 on 2024-04-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("receivables", "0004_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="receivables.province",
            ),
        ),
    ]
