# Generated by Django 4.1.2 on 2024-02-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("module_to_execute_location", models.CharField(max_length=255)),
                ("code", models.CharField(default="ROC", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalActionProxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("module_to_execute_location", models.CharField(max_length=255)),
                ("code", models.CharField(default="ROC", max_length=255)),
            ],
        ),
    ]
