# Generated by Django 4.1.2 on 2024-02-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalticketproxy",
            name="name",
            field=models.CharField(default="Approval Ticket Proxy", max_length=255),
        ),
    ]
