# Generated by Django 4.1.2 on 2024-02-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_tickets", "0002_approvalticketproxy_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalticketproxy",
            name="code",
            field=models.CharField(default="MEMBER_BLUEPRINT", max_length=255),
        ),
    ]
