# Generated by Django 4.1.2 on 2024-02-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("approval_groups", "0002_approvalgroupproxy"),
        ("approval_group_levels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalgrouplevelproxy",
            name="approval_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_group_levels",
                to="approval_groups.approvalgroupproxy",
            ),
            preserve_default=False,
        ),
    ]
