# Generated by Django 4.1.2 on 2024-02-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvers", "0001_initial"),
        ("approval_group_levels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalGroupMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_status", models.CharField(max_length=255)),
                ("action_message", models.CharField(max_length=255)),
                (
                    "approval_group_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_group_marks",
                        to="approval_group_levels.approvalgrouplevel",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_group_marks",
                        to="approvers.approver",
                    ),
                ),
            ],
        ),
    ]
