# Generated by Django 5.0.4 on 2024-04-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="acc_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bank",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bank",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
