# Generated by Django 5.0.4 on 2024-04-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivables", "0002_transaction_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount_paid",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
