# Generated by Django 5.0.4 on 2024-04-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivables", "0002_bank_acc_number_bank_address_alter_bank_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount_paid",
            field=models.FloatField(default=0.0),
        ),
    ]
