# Generated by Django 5.0.4 on 2024-04-22 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivables", "0003_transaction_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="receivables.bank",
            ),
        ),
    ]
