# Generated by Django 5.0.4 on 2024-04-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivables", "0003_alter_transaction_amount_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
