# Generated by Django 5.0.4 on 2024-04-22 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receivables", "0004_payment_bank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="amount_paid",
        ),
    ]
